---

- name: Pacman mirrorlist setup
  ansible.builtin.template:
    src: mirrorlist.j2
    dest: /etc/pacman.d/

- name: Pacman config setup
  ansible.builtin.template:
    src: pacman.conf.j2
    dest: /etc/pacman.conf

- name: Update pacman package cache
  community.general.pacman:
    update_cache: true
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Perform full system upgrade
  community.general.pacman:
    update_cache: true
    upgrade: true
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  notify:
    - rkhunter propupdate

- name: Install base packages
  community.general.pacman:
    name: "{{ base_packages }}"
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  notify:
    - rkhunter propupdate

- name: Install yay as aur helper
  aur:
    name: yay
    user: "{{ user.name }}"
    skip_pgp: true
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  
- name: Install microcode updates for intel (if necessary)
  community.general.pacman:
    name: intel-ucode
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  notify:
    - update grub
    - update syslinux
  when: system.processor == "intel"

- name: Install microcode updates for amd (if necessary)
  community.general.pacman:
    name: amd-ucode
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  notify:
    - update grub
    - update syslinux
  when: system.processor == "amd"

- name: Enable cronie server
  ansible.builtin.service: name=cronie state=started enabled=true

- name: Enable paccache timer
  ansible.builtin.service: name=paccache.timer state=started enabled=true
