---

- name: install fonts
  community.general.pacman:
    name:
      - ttf-dejavu
      - ttf-liberation
      - ttf-droid
      - ttf-font-awesome
      - noto-fonts-cjk
      - noto-fonts-emoji
      - fontconfig
      - xorg-font-util
      - powerline-fonts
      - ttf-nerd-fonts-symbols-mono
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
