---
- name: Install telegram-desktop and discord
  pacman:
    name:
      - telegram-desktop
      - discord
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Install Slack Desktop
  aur: name={{ item }} user={{ user.name }}
  with_items:
    - slack-desktop
  register: slackinstall
  until: slackinstall is success
  retries: 10
  delay: 2