---

- name: Install Wez terminal emulator
  aur: name={{ item }} user={{ user.name }}
  with_items:
    - wezterm-git
  register: wezinstall
  until: wezinstall is success
  retries: 10
  delay: 2

- name: install tmux terminal multiplexer
  community.general.pacman:
    name: tmux
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
